apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 643080896915.dkr.ecr.us-east-1.amazonaws.com/worker-repository:v10
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 1
